const String TWEETS_TEST_ACTION = 'TWEETS_TEST_ACTION';
const String TIMELINE_REQUEST_NEXT_PAGE_PERFORMED = 'TIMELINE_REQUEST_NEXT_PAGE_PERFORMED';
const String TIMELINE_REQUEST_NEXT_PAGE_FAILURE = 'TIMELINE_REQUEST_NEXT_PAGE_FAILURE';
const String TIMELINE_REQUEST_NEXT_PAGE_SUCCESS = 'TIMELINE_REQUEST_NEXT_PAGE_SUCCESS';
const String TIMELINE_REQUEST_SUCCESS = 'TIMELINE_REQUEST_SUCCESS';
const String TIMELINE_REQUEST_FAILURE = 'TIMELINE_REQUEST_FAILURE';
const String TIMELINE_REQUEST_PERFORMED = 'TIMELINE_REQUEST_PERFORMED';